version: "3"
services:
  server:
    container_name: goods_server
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - "./server:/usr/src/app"
    links:
      - mongo
  client:
    container_name: goods_client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
