export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCT_SAVING = 'PRODUCT_SAVING';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_SAVING_ERR = 'PRODUCT_SAVING_ERR';
export const RESET_BOOLEAN_STATUS = 'RESET_BOOLEAN_STATUS';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';

// ============
export const PRODUCT_LIST_GET_REQUEST = 'PRODUCT_LIST_GET_REQUEST';
export const PRODUCT_LIST_GET_SUCCESS = 'PRODUCT_LIST_GET_SUCCESS';
export const PRODUCT_LIST_GET_ERROR = 'PRODUCT_LIST_GET_ERROR';
export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';
export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';
export const RESET = 'RESET';
