export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCT_SAVING = 'PRODUCT_SAVING';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_SAVING_ERR = 'PRODUCT_SAVING_ERR';
export const RESET_BOOLEAN_STATUS = 'RESET_BOOLEAN_STATUS';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
